version: '3'
services:
  golang:
    image: qnib/uplain-golang:1.9@sha256:2261b812e1f3b6c9c49d4f8795a30432778a97fb856c73c54f57dd36831af948
    networks:
      - kafka_default
    volumes:
      - ${GOPATH}/src/:/usr/local/src/
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      disable: true
    command: wait.sh

networks:
  kafka_default:
    external: true
