zookeeper:
    image: qnib/plain-zookeeper
    net: "host"
    ports:
      - "2181:2181"
broker:
    image: qnib/plain-kafka
    net: "host"
    ports:
      - "9092:9092"
    extra_hosts:
      - "moby:127.0.0.1"
    environment:
      ZK_SERVERS: "moby"
manager:
    image: qnib/plain-kafka-manager:1.3.3.7
    ports:
      - "9000:9000"
    environment:
      ZK_SERVER: "moby:2181"

